version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"  
    volumes:
      - .:/app  
      - /app/node_modules  
    command: npm start 
